Repository salle-malle/front, pull requests merged in 2025-07, with the labels that each got.

#14 Feat : 로그인 화면 UI 구현
  src/app/login/page.tsx
  src/components/top-navigation.tsx
Labels: ✨feature, 🎨FE

#15 Feat : 회원가입 UI 구현
  package.json
  pnpm-lock.yaml
  src/app/login/page.tsx
  src/app/signup/accountRegister/page.tsx
  src/app/signup/page.tsx
  src/app/signup/phoneNumber/page.tsx
  src/app/signup/userAccount/page.tsx
  src/components/top-navigation.tsx
Labels: ✨feature, 🎨FE

#17 Fix : scrap 그룹이 두 번 랜더링 되는 코드를 수정합니다
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/cards/page.tsx
  src/app/home/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/scrap/page.tsx
  src/stores/memberStore.ts
  src/types/ApiResponse.ts
  src/types/Member.ts
  src/types/ScrapGroup.ts
Labels: 🐞bug

#33 Feat : 메인페이지 UI 화면을 구현한다
  package.json
  pnpm-lock.yaml
  public/ticker-icon/APPL.png
  public/ticker-icon/META.png
  public/ticker-icon/TSLA.png
  public/ticker-icon/WMT.png
  src/app/home/page.tsx
  src/components/ui/asset-chart.tsx
  src/components/ui/asset-summary.tsx
  src/components/ui/chart-period.tsx
  src/components/ui/info-tabs.tsx
  src/components/ui/news-item.tsx
  src/components/ui/news-slider.tsx
  src/components/ui/stock-list.tsx
  src/components/ui/tab-content.tsx
  src/components/ui/tab-slider.tsx
Labels: ✨feature, 🎨FE

#37 Feat : 메인페이지 백엔드 API 연결
  public/ticker-icon/AAPL.png
  public/ticker-icon/AMZN.png
  public/ticker-icon/BRK.B.png
  public/ticker-icon/GOOGL.png
  public/ticker-icon/IBM.png
  public/ticker-icon/INTC.png
  public/ticker-icon/MCD.png
  public/ticker-icon/MSFT.png
  public/ticker-icon/NDAQ.png
  public/ticker-icon/NFLX.png
  public/ticker-icon/NVDA.png
  public/ticker-icon/QQQ.png
  public/ticker-icon/TMUS.png
  public/ticker-icon/VOO.png
  src/app/home/page.tsx
  src/components/ui/asset-summary.tsx
  src/components/ui/info-tabs.tsx
  src/components/ui/stock-list.tsx
  src/components/ui/tab-content.tsx
  src/components/ui/tab-slider.tsx
Labels: ✨feature, 🎨FE

#44 Feat/mypage
  src/app/profile/edit-investment/page.tsx
  src/app/profile/edit-nickname/page.tsx
  src/app/profile/page.tsx
Labels: ✨feature, 🎨FE

#59 Feat/notification mypage
  src/app/cards/page.tsx
  src/app/notifications/page.tsx
  src/app/profile/page.tsx
  src/components/top-navigation.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/useNotification.tsx
Labels: ✨feature, 🎨FE

#62 Feat [: 회원가입 API를 연결한다
  pnpm-lock.yaml
  src/app/login/page.tsx
  src/app/signup/accountRegister/page.tsx
  src/app/signup/page.tsx
  src/app/signup/phoneNumber/page.tsx
  src/app/signup/userAccount/page.tsx
  src/stores/signupStore.ts
Labels: ✨feature, 🎨FE

#83 Feat : 공시 상세페이지 UI를 구현하고 백엔드와 통신한다
  src/app/disclosure/[id]/page.tsx
  src/app/home/page.tsx
  src/components/ui/info-tabs.tsx
Labels: ✨feature, 🛠️BE

#84 Feat/notification earning disclosure
  public/characters/moli-profile.png
  public/characters/pli-profile.png
  public/characters/shoo-profile.png
  public/characters/sol-profile.png
  src/app/notifications/page.tsx
  src/app/profile/page.tsx
  src/app/stock/[code]/page.tsx
  src/hooks/use-toast.ts
Labels: 🎨FE

#95 Feat : 공시 캘린더 백엔드 API를 연결한다 & 캘린더 UI를 수정한다
  src/app/calendar/CalendarClient.tsx
  src/app/disclosure/[id]/page.tsx
Labels: ✨feature, 🎨FE

#98 Style/UI markdown summary card
  package.json
  pnpm-lock.yaml
  src/app/cards/page.tsx
  src/components/ui/CardViewer.tsx
  tailwind.config.ts
Labels: 🎨FE

#116 Feat/total summary render
  src/app/home/page.tsx
  src/components/ui/asset-chart.tsx
  src/components/ui/summary-slider.tsx
Labels: ✨feature, 🎨FE

#117 v1.0.0
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  public/ticker-icon/UBER.png
  public/ticker-icon/V.png
  src/app/calendar/CalendarClient.tsx
  src/app/cards/page.tsx
  src/app/disclosure/[id]/page.tsx
  src/app/globals.css
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/my-stocks/page.tsx
  src/app/notifications/page.tsx
  src/app/page.tsx
  src/app/profile/edit-investment/page.tsx
  src/app/profile/edit-nickname/page.tsx
  src/app/scrap/page.tsx
  src/app/signup/accountRegister/page.tsx
  src/app/signup/page.tsx
  src/app/signup/phoneNumber/page.tsx
  src/app/signup/userAccount/page.tsx
  src/components/scrap/ScrapCardDetailModal.tsx
  src/components/scrap/ScrapCardViewer.tsx
  src/components/scrap/ScrapDateSelector.tsx
  src/components/scrap/ScrapGroupSelector.tsx
  src/components/scrap/ScrapStockList.tsx
  src/components/scrap/ScrapStockSelector.tsx
  src/components/scrap/TrebleSelector.tsx
  src/components/top-navigation.tsx
  src/components/ui/AddGroupDialog.tsx
  src/components/ui/CardDetailModal.tsx
  src/components/ui/CardViewer.tsx
  src/components/ui/DateSelector.tsx
  src/components/ui/DualSelector.tsx
  src/components/ui/ScrapGroupDialog.tsx
  src/components/ui/SelectedDateDisplay.tsx
  src/components/ui/StockSelector.tsx
  src/components/ui/asset-chart.tsx
  src/components/ui/summary-slider.tsx
Labels: ✨feature, 🎨FE

#133 Feat : UI 디테일을 잡는다
  src/app/disclosure/[id]/page.tsx
  src/app/home/page.tsx
  src/app/signup/accountRegister/page.tsx
  src/app/signup/page.tsx
  src/app/signup/phoneNumber/page.tsx
  src/app/signup/userAccount/page.tsx
  src/components/ui/info-tabs.tsx
Labels: ✨feature, 🎨FE
